apiVersion: apps/v1
kind: Deployment

metadata:
  name: celery-worker

spec:
  replicas: 2

  selector:
    matchLabels:
      app: celery-worker

  template:

    metadata:
      labels:
        app: celery-worker

    spec:

      containers:
        - name: celery-worker

          image: qa-runtime:latest

          imagePullPolicy: Never

          command:
            - celery

          args:
            - -A
            - src.tasks.test_tasks
            - worker
            - --pool=solo
            - --loglevel=info

          env:
            - name: DATABASE_URL
              value: postgresql://qa_user:qa_password@postgres:5432/qa_runtime

            - name: REDIS_URL
              value: redis://redis:6379/0